version: "2" # specify docker-compose version

# Define the services/containers to be run
services:
    transfer-portal-api: 
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:3000"
        volumes:
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    node_modules: